### ISSUE TITLE
[BUG] REFILLINV clears the inventory slot

### ISSUE THREAD

**Issue by seapsychodonniedarko** [ThatFinnDev/SR2E#30]
**Describe the bug**
With the latest build, using the REFILLINV [SLOT] command clears the inventory instead of refilling it. The attached screenshots are the before/after I use it on the second slot (Hunter plort)

**To Reproduce**
1. Have an item in the Vacpack
2. Open console and type (or autofill) REFILLINV followed by the slot number
3. Slot is now empty

**Expected behavior**
Refilling the slot to max capacity instead of emptying it

**Screenshots**
![20240606162734_1](https://github.com/ThatFinnDev/SR2E/assets/10743311/96848342-4cee-4e26-9b17-f8f4feec949f)
![20240606162746_1](https://github.com/ThatFinnDev/SR2E/assets/10743311/259782cf-5839-42f6-bbf6-d8a7190488cf)

**Comment by ThatFinnDev** [comment]
Thanks for reporting. I am currently not at home but once I am, I will fix it and release an update
