### ISSUE TITLE
"fxplayer" command doesn't work

### ISSUE THREAD

**Issue by Darkminer86** [ThatFinnDev/SR2E#35]
Hi. Whenever I try to use the "fxplayer" command, It will say it's "successfully playing FX", but then I get another message immediately saying "You're not looking at anything!". Am I just using the command wrong, or do I need to do something else, such as binding it to a key or having the game NOT freeze while the console is open

**Comment by ThatFinnDev** [comment]
I see it. It's a bug. The "You're not looking at anything!" message is also sent when playing an fx successfully. It'll be fixed in the next update
